---
title: "wk5_prac"
author: "chris"
date: "2021/11/15"
output: html_document
---
```{r}

```

# Notes

bedroom is at ward - convert to borough
could also probably just use Local Area District Data
Hotel is points - summarise over borough
Airbnb is points - summarise over borough


```{r library}
library(sf)
library(tidyverse)
library(janitor)
library(tmap)
library(tmaptools)
library(here)
```

```{r wards etc}
Londonboroughs <- st_read(here::here('data',
                               'statistical-gis-boundaries-london',
                               'ESRI',
                               'London_Borough_Excluding_MHW.shp'))%>%
  clean_names()%>%
  st_transform(.,27700)


Londonwards <- st_read(here::here('data',
                               'statistical-gis-boundaries-london',
                               'ESRI',
                               'London_ward.shp'))%>%
  clean_names()%>%
  st_transform(.,27700)
```
```{r accomodation data}
OSM <- st_read(here::here('data',
                          'greater-london-latest-free.shp',
                          'gis_osm_pois_a_free_1.shp'))%>%
  st_transform(.,27700)           #crs转换为british national grid 27700

Airbnb <- read_csv(here::here('data',
                              'listings',
                              'listings.csv'))%>%
  st_as_sf(.,coords=c('longitude','latitude'),
           crs=4326)%>%
  st_transform(.,27700)

Worldcities <- st_read(here::here('data',
                                  'World_Cities',
                                  'World_Cities.shp'))

ward_beds <- read_csv(here::here('data',
                              'ward_bedrooms.csv'))%>%
  clean_names()
```
```{r bed to borough}
bed_borough <- Londonwards %>%
    merge(.,
       ward_beds, 
        by.x="gss_code", 
        by.y="geography_code")%>%
  clean_names()%>%
  group_by(lb_gss_cd,borough)%>%
  summarise(total_beds_per_borough = sum(bedrooms_all_categories_number_of_bedrooms_measures_value, na.rm = TRUE))%>%
  st_drop_geometry()
            
```
```{r airbnb_borough}
Airbnb_borough <- Airbnb%>%
  filter(room_type=='Entire home/apt')%>%
  filter(availability_365=='365')%>%
  st_join(Londonboroughs,.)%>%
  group_by(gss_code)%>%
  summarise(airbnbcount=n())%>%
  st_drop_geometry()
  
```

```{r osm_hotels}
OSM_hotels <- OSM%>%
  filter(fclass =='hotel') %>%
  st_join(Londonboroughs,.)%>%
  group_by(gss_code)%>%
  summarise(hotelcount=n())%>%
  st_drop_geometry()
```

```{r all together}
all_data_one <- Londonboroughs%>%
  merge(.,
        bed_borough,
        by.x='gss_code',
        by.y='lb_gss_cd')

all_data_two <- all_data_one%>%
  left_join(.,
            Airbnb_borough,
            by=c('gss_code'='gss_code'))

all_data_three <- all_data_two%>%
  left_join(.,
            OSM_hotels,
            by=c('gss_code'='gss_code'))

map_norm <- all_data_three%>%
  mutate(airbnb_norm=airbnbcount/total_beds_per_borough)%>%
  mutate(hotel_norm=hotelcount/total_beds_per_borough)

```

```{r extra_info}
Worldcities_extract <- Worldcities%>%
  clean_names()%>%
  filter(cntry_name=='United Kingdom')%>%
  filter(city_name=='London'|city_name=='Birmingham'|city_name=='Edinburgh')

UK_outline <- st_read(here::here('data',
                                 'gadm36_GBR_shp',
                                 'gadm36_GBR_0.shp'))%>%
  st_transform(.,27700)
  
```
```{r mapping}
tmap_mode('plot')

#使用Jenks自然简短法
#install.packages("BAMMtools")
#library(BAMMtools)
#t <- getJenksBreaks(map_norm$airbnb_norm,k-5)

tm1 <- tm_shape(map_norm)+
  tm_polygons('airbnb_norm',
              style='jenks',#自然间断分裂法
              palette='PuBu')+
  #tm_legend(show = FALSE)+#图例
  tm_layout(frame = FALSE)+#外边框
  tm_credits('(a)',position = c(0,0.85),size=1.5)#左下角为（0，0），右上角为（1，1）

tm2 <- tm_shape(map_norm)+
  tm_polygons('hotel_norm',
              style='jenks',
              palette='PuBu')+
  #tm_legend(show=FALSE)+
  tm_layout(frame = FALSE)+
  tm_credits('(b)',position = c(0,0.85),size = 1.5)

newbb <- c(xmin=-296000,ymin=5408,xmax=655696,ymax=1000000)

UK_outlinecrop <- UK_outline$geometry%>%
  st_crop(.,newbb)#裁成特定矩形
  
tm3 <- tm_shape(UK_outlinecrop)+
  tm_polygons(col='darkslategray1')+
  tm_layout(frame = FALSE)+
  tm_shape(Worldcities_extract)+
  tm_symbols(col = 'red',scale=.5)+
  tm_text('city_name',xmod = -1,ymod = -0.5)

legend <- tm_shape(map_norm)+
  tm_polygons('hotel_norm',
              style='jenks',
              palette='PuBu')+
  tm_scale_bar(position = c(0.2,0.04),text.size = 0.6)+
  tm_compass(north = 0,position = c(0.65,0.6))+
  tm_layout(legend.only = TRUE,legend.position = c(0.2,0.25),asp =0.1)+
  tm_credits('(c) OSM contributor and Airbnb',position = c(0.0,0.0))

t=tmap_arrange(tm1,tm2,tm3,legend,ncol =2 )

```

```{r insetmap}
Londonbb <- st_bbox(map_norm)%>%
  st_as_sfc()

tmmain <- tm_shape(map_norm,bbox = Londonbb)+
  tm_polygons('airbnb_norm',
              style='jenks',
              palette='PuBu')+
  tm_scale_bar(position = c('left','bottom'),text.size = .75)+
  tm_layout(legend.position=c(0.6,0.8),
            legend.text.size = .75,
            legend.title.size = 1.1,
            frame = FALSE)+
  tm_credits('(c) OSM contributors and Airbnb',position = c(0.0,0.0))+
  tm_compass(type = '8star',position = c(0.06,0.1))+
  tm_layout(inner.margins = c(0.04,0.04,0.04,0.4))

inset <- tm_shape(UK_outlinecrop)+
  tm_polygons(col='darkslategray1',lwd=3)+
  tm_shape(Londonbb)+
  tm_borders(col='gray40',lwd=3)+
  tm_layout(frame=FALSE,bg.color = 'transparent')+
  tm_shape(Worldcities_extract)+
  tm_symbols(col='red',scale=.5)+
  tm_text('city_name',xmod=-1.5,ymod=-0.5)
  
library(grid)
tmmain
print(inset,vp=viewport(0.86,0.29,width=0.5,height=0.55))
```
```{r export map}
tmap_save(t, 'hotelsandairbnbR.png')

library(grid)
tmap_save(insets_tm = inset,insets_vp=viewport(x=0.86, y=0.29, width=.5, height=.55), filename="test.pdf", dpi=600)
```
```{r basic interactive map}
tmap_mode("view")

tm_shape(map_norm) + 
  tm_polygons("hotel_norm",
              style='jenks') 
```
```{r advanced interactive map}
# library for pop up boxes
library(leafpop)
library(leaflet)

#join data
Joined <- Airbnb%>%
  st_join(., OSM_hotels, join = st_equals)%>%
  dplyr::select(GSS_CODE.x, NAME.x, `Accomodation count.x`, `Accomodation count.y`)%>%
  dplyr::rename(`GSS code` =`GSS_CODE.x`,
                `Borough` = `NAME.x`,
                `Airbnb count` = `Accomodation count.x`,
                `Hotel count`= `Accomodation count.y`)%>%
  st_transform(., 4326)
  
  
#remove the geometry for our pop up boxes to avoid
popupairbnb <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Airbnb count`, Borough)%>%
  popupTable()

popuphotel <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Hotel count`, Borough)%>%
  popupTable()

tmap_mode("view")

# set the colour palettes using our previously defined breaks


pal1 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Airbnb count`, bins=breaks)

pal1 <-colorBin(palette = "YlOrRd", domain=Joined$`Airbnb count`, bins=breaks)

pal2 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Hotel count`, bins=breaks)


map<- leaflet(Joined) %>%
  # add basemap options
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB")%>%
  
  #add our polygons, linking to the tables we just made
  addPolygons(color="white", 
              weight = 2,
              opacity = 1,
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,
              fillColor = ~pal2(`Airbnb count`),
              group = "Airbnb")%>%
  
  addPolygons(fillColor = ~pal2(`Hotel count`), 
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,group = "Hotels")%>%
  # add a legend
  addLegend(pal = pal2, values = ~`Hotel count`, group = c("Airbnb","Hotel"), 
            position ="bottomleft", title = "Accomodation count") %>%
  # specify layers control
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "Toner Lite", "CartoDB"),
    overlayGroups = c("Airbnb", "Hotels"),
    options = layersControlOptions(collapsed = FALSE)
  )

# plot the map
map
```

